app/routes.py
from flask import (
    render_template,
    redirect,
    url_for,
    Blueprint,
)
from app.forms import LoginForm
from app.models import Child, Proctor, Session
from app import db
from flask_login import login_required, login_user, logout_user

bp = Blueprint("routes", __name__)


@bp.route("/")
@bp.route("/index")
@login_required
def index():
    return render_template("landingpage.html", title="Home")


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        child_id = form.child_id.data
        proctor_id = form.proctor_id.data

        # Check if the child is in the database - if they are not, then add
        # them. We might want to change this behavior later so that if they are
        # not in the database, we do not allow them to log in.
        if Child.query.filter_by(id=child_id).first() is None:
            child = Child(id=child_id)
            db.session.add(child)
            db.session.commit()

        # Check if the proctor is in the database - if they are not, then add
        # them. We might want to change this behavior later so that if they are
        # not in the database, we do not allow them to log in.
        if Proctor.query.filter_by(id=proctor_id).first() is None:
            proctor = Proctor(id=proctor_id)
            db.session.add(proctor)
            db.session.commit()

        session_db_entry = Session(child_id=child_id, proctor_id=proctor_id)
        db.session.add(session_db_entry)
        db.session.commit()

        child = Child.query.filter_by(id=form.child_id.data).first()
        if child is None:
            print("Invalid child_id or password")
            return redirect(url_for("routes.login"))

        login_user(child)
        return redirect(url_for("routes.index"))

    return render_template("login.html", title="Sign In", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("routes.index"))

app/templates/base.html
<html>
    {% include "head.html" %}
    <body>
        {% include "navbar.html" %}
        <div class="container" style="text-align: center;">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

app/templates/breadth.html
{% extends "base.html" %}

{% macro imageContainer(i) -%}
    <td>
        <a href="#">
            <img id = "position_{{ i }}" 
                 class = "sourceImage img-fluid"
                 src="" width="300"/>
        </a>
    </td>
{%- endmacro %}

{% block content %}

<script src={{ url_for("static", filename="scivocab/js/breadth.js") }}></script>

<div class="row p-1">
    <div class="col">
        <h1 id="header" style="display:inline;"></h1>
        {% include "playButton.html" %}
    </div>
</div>
<div class="row">
    <div class="col justify-content-md-center">
        <table style="margin:auto;">
            <tr>
                {{ imageContainer(0) }}
                {{ imageContainer(1) }}
            </tr>
            <tr>
                {{ imageContainer(2) }}
                {{ imageContainer(3) }}
            </tr>
        </table>
    </div>
</div>

<div class="row justify-content-md-center p-1">
    <div class="col">
        <button type="button" id="nextWordButton"
            class="btn btn-primary">
            Next
        </button>
    </div>
</div>

{% endblock %}

app/templates/definition.html
{% extends "base.html" %}

{% block content %}

    <script script src={{ url_for("static", filename="scivocab/js/definition.js") }}></script>
    <div class="row p-3">
        <div class="col">
            <h1 id="header" style="display:inline;"></h1>
            {% include "playButton.html" %}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <textarea
                id="definition"
                placeholder="Enter definition here"
                style="width:100%; height: 24rem; font-size: 1.5rem;"
                autofocus
            ></textarea>
        </div>
    </div>

    <div class="row justify-content-md-center p-3">
        <div class="col">
            <button type="button" id="nextWordButton"
                                    class="btn btn-primary">
                Next
            </button>
        </div>
    </div>

{% endblock %}

app/templates/depth.html
{% extends "base.html" %}

{% macro sourceImageContainer(i) -%}
    <td>
        <a href="#">
            <div class="sourceImageContainer border p-1">
            <img id = "position_{{ i }}" 
                 class = "sourceImage img-fluid"
                 src={{ url_for("static", filename="scivocab/images/dv_placeholder.gif") }} 
                 draggable="true"
                 />
            </div>
        </a>
    </td>

{%- endmacro %}

{% macro targetImageContainer(i) -%}
    <div class="border targetImageContainer p-1" 
            id = "target_position_{{ i }}">
            <img class="targetImage img-fluid" 
                id = "target_image_{{ i }}"
                src={{ url_for("static", filename="scivocab/images/dv_placeholder.gif") }}
            />
    </div>
{%- endmacro %}

{% block content %}

<script src={{ url_for("static", filename="scivocab/js/depth.js") }}></script>

<div class="row" style="width:900; margin: auto">
    <div class="col-10">
        <div class="row p-1">
            <div class="col">
                <h1 id="header" style="display:inline;"></h1>
                {% include "playButton.html" %}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ sourceImageContainer(0) }}
            </div>
            <div class="col">
                {{ sourceImageContainer(1) }}
            </div>
        </div>

        <div class="row">
            <div class="col">
                {{ sourceImageContainer(2) }}
            </div>
            <div class="col">
                {{ sourceImageContainer(3) }}
            </div>
        </div>
        <div class="row p-2">
            <div class="col">
                <button type="button" id="nextWordButton"
                                    class="btn btn-primary">
                    Next
                </button>
            </div>
        </div>

    </div>

    <div class="col-2" style="margin:auto;">
        <div class="row p-1">
            <div><b>Best</b></div>
        </div>
        {% for i in range(4) %}
            <div class="row"> {{ targetImageContainer(i) }} </div>
        {% endfor %}
        <div class="row p-1">
            <div><b>Worst</b></div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/fun_fact.html
{% extends "base.html" %}

{% block content %}


<div class="row" style="margin-top: 2rem;">
    <div class="col">
        <img id = "fun_fact" class = "img-fluid" src="{{ image }}" width="600"/>
    </div>
</div>

<div class="row justify-content-md-center p-1">
   <div class="col">
       {% if not is_final %}
       <a id="{{task_id}}" href="{{ url_for(task_id +'.main') }}" class="btn btn-primary btn-lg">
            Continue
       </a>
       {%else%}
       <div class="row" style="font-size:2rem;"><div class="col">You're all done!</div></div>
       <div class="row">
           <div class="col">
            <a id="{{task_id}}" href="{{ url_for('routes.index') }}" class="btn btn-primary btn-lg">
                    Return to landing page
            </a>
           </div>
       </div>
       {% endif %}
   </div>
</div>

{% endblock  %}

app/templates/head.html
<head>
    <!-- Load jQuery from a CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js">
    </script>

    <!-- Import Bootstrap stylesheet from a CDN -->
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
    crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>

    <!-- Import custom stylesheet -->
    <link rel="stylesheet"  href={{ url_for('static', filename='style.css') }}>
    <link rel="shortcut icon" href="{{ url_for('static', filename='scivocab/favicon.ico') }}">
    {% if title %}
        <title>Scivocab | {{ title }} </title>
    {% else %}
        <title>Scivocab</title>
    {% endif %}
</head>

app/templates/landingpage.html
{% extends "base.html" %}

{% block content %}

    <div class="container-fluid" style="text-align: center">
        <div class="row">
            <div class="col">
                <p style="font-size:1.5rem;">Select a task below:</p>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <img src={{ url_for("static",
                filename="scivocab/women_scientist_images/b1_flossie_wong_staal.jpg")
                }}  alt="Flossie" class="image">
                <a href="{{ url_for('breadth.main') }}" class="btn
                btn-outline-primary btn-lg">Breadth Task
                </a>
            </div>

            <div class="col">
                <img 
                    src={{ url_for("static", filename="scivocab/women_scientist_images/d1_annie_easley.jpg")}}
                    alt="Annie" class="image">
                <a href="{{ url_for('depth.main') }}" class="btn
                btn-outline-primary btn-lg">Depth Task</a>
            </div>
            
            <div class="col">
                <img src={{ url_for("static",
                filename="scivocab/women_scientist_images/def1_kalpana_chawla.jpg")
                          }}  alt="FLossie" class="image">
                <a href="{{ url_for('definition.main') }}" class="btn
                    btn-outline-primary btn-lg">Definition Task</a>
            </div>
        </div>
    </div>

<style>
.container {
  position: relative;
  width: 50%;
}

.image {
  display: block;
  width: 100%;
  height: auto;
  padding: 5px;
}

.overlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  height: 100%;
  width: 100%;
  opacity: 0;
  transition: .5s ease;
  background-color: #005d9c;
}

.container:hover .overlay {
  opacity: 1;
}

.text {
  color: white;
  font-size: 20px;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}


{% block content %}
    
    <title>{% block title %}{% endblock %}Login - Scientific Vocabulary Task</title>
    <header>
        {% block header %}{% endblock %}
    </header>
	
    
    <div class="row" style="padding: 2rem;">
        <div class="col">
            <img src={{ url_for("static", filename="scivocab/images/ScienceVocabStudy.png") }}
            style="width:50%;"></img>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="" method="post" novalidate>
                {{ form.hidden_tag() }} 
                <p>
                    {{ form.child_id.label }}<br>
                    {{ form.child_id(size=20) }}<br>
                    {% for error in form.child_id.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </p>
                <p>
                    {{ form.proctor_id.label }}<br>
                    {{ form.proctor_id(size=20) }}<br>
                    {% for error in form.proctor_id.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}

                </p>
                {{ form.submit() }}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('routes.index') }}">SciVocab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
        {% if current_user.is_authenticated %}
            <span class="navbar-text">Child ID: {{ current_user.id }}</span>
            <span class="navbar-text">
                <a class="nav-link" href="{{ url_for('routes.logout') }}">
                    Logout
                </a>
            </div>
        {% endif %}
    </div>
  </div>
</nav>

app/templates/playButton.html
<button id="playButton"
        style="background-image: url('{{ url_for("static", filename="scivocab/images/speaker_icon.png") }}');">
</button>